allowedLicenses: []
excludedPackages: []
include:
- url: https://raw.githubusercontent.com/nbyl/license-check-config/main/commercial-use/license-check-python.yaml
- url: https://raw.githubusercontent.com/nbyl/license-check-config/main/open-source/license-check-python.yaml
