-   id: check-license
    name: Check against license whitelist
    description: This hook scans the local Pipfile against a configured license whitelist.
    entry: python -m pre_commit_hooks.license_check
    files: Pipfile
    language: python
