-   id: check-license
    name: Check against license whitelist
    description: This hook scans the local Pipfile against a configured license whitelist.
    entry: check_license
    language: python
    files: Pipfile